version: 0.0
os: linux

files:
  - source: files/newpage.html
    destination: /var/www/html

permission:
  - object: /var/www/html
    pattern: newpage.html
    mode: 0755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
